[package]
name = "web-command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
rocket = "0.5.0-rc.2"
serde = "1.0.144"
serde_json = "1.0.85"
urlencoding = "2.1.2"
thhp = "0.2.0"
